import { Box, Clock3, Globe2, Search, Smile, TrendingUp, Users } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Area, AreaChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { GeographicDistribution } from "../../components/usage/GeographicDistribution";
import { usageSeries } from "../../data/mock/customer360Fixtures";
import { Button, Ring, Status, TextAction, WorkspaceKpi, WorkspaceKpis, WorkspacePageHeader, WorkspacePanel } from "../../components/workspace/WorkspaceUi";

export function UsagePage() {
  const navigate = useNavigate();
  return (
    <div className="workspace-screen">
      <WorkspacePageHeader actions={<input aria-label="Usage date range" className="date-control" readOnly value="May 21 – May 27, 2024" />} description="Track how knowledge assets are being used, by whom, and derive actionable insights." title="Usage & Insights" />
      <WorkspaceKpis>
        <WorkspaceKpi icon={TrendingUp} label="Total Consumption" note="↑ 18.6% vs last 7 days" tone="purple" trend="up" value="24.6K" />
        <WorkspaceKpi icon={Users} label="Active Consumers" note="↑ 12.0% vs last 7 days" tone="blue" trend="up" value={128} />
        <WorkspaceKpi icon={Box} label="Applications" note="No change vs last 7 days" tone="green" value={8} />
        <WorkspaceKpi icon={Globe2} label="API / Endpoint Calls" note="↑ 22.4% vs last 7 days" tone="orange" trend="up" value="7.3K" />
        <WorkspaceKpi icon={Clock3} label="Avg. Response Time" note="↓ 8.3% vs last 7 days" tone="blue" trend="down" value="412 ms" />
        <WorkspaceKpi icon={Smile} label="User Satisfaction" note="↑ 0.3 vs last 7 days" tone="green" trend="up" value="4.6 / 5" />
      </WorkspaceKpis>
      <div className="usage-workspace-grid">
        <WorkspacePanel action={<select aria-label="Consumption period" className="workspace-select"><option>Last 7 Days</option></select>} title="Consumption Over Time"><div className="workspace-chart workspace-chart--large"><ResponsiveContainer height="100%" width="100%"><AreaChart data={usageSeries}><defs><linearGradient id="consumption" x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor="#7c3aed" stopOpacity={0.16}/><stop offset="95%" stopColor="#7c3aed" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#eef0f2" vertical={false}/><XAxis dataKey="day" tick={{fontSize:9}}/><YAxis tick={{fontSize:9}}/><Tooltip/><Legend wrapperStyle={{fontSize:9}}/><Area dataKey="consumption" fill="url(#consumption)" isAnimationActive={false} stroke="#7c3aed" strokeWidth={2}/><Area dataKey="api" fillOpacity={0} isAnimationActive={false} stroke="#2563eb"/><Area dataKey="search" fillOpacity={0} isAnimationActive={false} stroke="#16a34a"/></AreaChart></ResponsiveContainer></div></WorkspacePanel>
        <WorkspacePanel action={<TextAction>View all</TextAction>} className="top-applications-panel" title="Top Applications"><table className="workspace-table compact-table"><thead><tr><th>Application</th><th>Type</th><th>Consumption</th><th>% of Total</th><th>Trend</th></tr></thead><tbody>{[["Customer 360 Assistant","RAG App","8.9K","36.2%"],["Policy Q&A Portal","Chatbot","5.2K","21.1%"],["Sales Copilot","AI App","3.4K","13.9%"],["Compliance Navigator","RAG App","2.1K","8.5%"],["Data Explorer","Analytics App","1.6K","6.5%"],["Others","—","3.4K","13.8%"]].map((row)=><tr key={row[0]}>{row.map((cell,index)=><td key={cell}>{index===0?<strong>{cell}</strong>:cell}</td>)}<td className="sparkline-text">⌁⌁⌁</td></tr>)}</tbody></table></WorkspacePanel>
        <WorkspacePanel action={<TextAction>View all</TextAction>} title="Top Knowledge Assets"><table className="workspace-table compact-table"><thead><tr><th>Asset</th><th>Type</th><th>Consumption</th><th>% of Total</th></tr></thead><tbody>{[["Customer","Entity","4.8K","19.5%"],["Policy","Entity","3.2K","13.0%"],["Product","Entity","2.9K","11.8%"],["Account","Entity","2.6K","10.6%"],["Customer_Policy","Relationship","2.2K","8.9%"]].map((row)=><tr key={row[0]}>{row.map((cell,index)=><td key={cell}>{index===0?<strong>{cell}</strong>:cell}</td>)}</tr>)}</tbody></table></WorkspacePanel>
        <WorkspacePanel title="Consumption by Consumer Type"><div className="health-layout"><Ring displayValue="24.6K" label="Total" tone="blue" value={72}/><div className="health-legend"><Status tone="purple">Internal Users <b>12.4K (50.4%)</b></Status><Status tone="blue">Applications <b>8.7K (35.4%)</b></Status><Status>APIs / Services <b>3.5K (14.2%)</b></Status></div></div></WorkspacePanel>
        <WorkspacePanel title="Geographic Distribution"><GeographicDistribution /></WorkspacePanel>
        <WorkspacePanel action={<TextAction>View all</TextAction>} title="Search & Query Insights"><div className="query-insights"><dl className="metric-list"><div><dt>Total Searches</dt><dd>6.2K</dd></div><div><dt>Zero Result Searches</dt><dd>312</dd></div><div><dt>Top Query Success Rate</dt><dd>92.4%</dd></div><div><dt>Avg. Results per Query</dt><dd>7.6</dd></div></dl><div><strong>Top Queries</strong>{["customer policy","account hierarchy","product catalog","policy coverage","customer segmentation"].map((query,index)=><p key={query}><Search size={12}/><span>{query}</span><b>{812-index*86}</b></p>)}</div></div></WorkspacePanel>
        <WorkspacePanel className="usage-insights" title="Insights & Recommendations"><ul className="insight-list"><li><TrendingUp/><span><strong>High growth in usage</strong><small>Total consumption increased by 18.6% compared to last 7 days.</small></span><Status tone="blue">Info</Status></li><li><Box/><span><strong>Popular asset: Customer entity</strong><small>Customer entity is the most consumed asset across applications.</small></span><Status>Insight</Status></li><li><Search/><span><strong>Improve search experience</strong><small>312 zero-result searches detected. Review synonyms and entity mappings.</small></span><Status tone="amber">Recommendation</Status></li></ul></WorkspacePanel>
        <WorkspacePanel className="adoption-panel" title="Adoption & Engagement"><div className="adoption-grid">{[["New Consumers","+21","↑ 16.6%"],["Returning Consumers","107","↑ 9.2%"],["Engagement Rate","67%","↑ 6.5%"],["Repeat Usage (7D)","58%","↑ 5.1%"]].map((item)=><div key={item[0]}><small>{item[0]}</small><strong>{item[1]}</strong><span>{item[2]}</span></div>)}</div><div className="tip-banner">Tip: Promote high-value assets as APIs for easier integration and wider adoption.<Button onClick={()=>navigate("../publish")}>Go to Publish & Serve →</Button></div></WorkspacePanel>
      </div>
    </div>
  );
}
